### ISSUE TITLE
CT200 firmware version 03.08.01

### ISSUE THREAD

**Issue by aleksandersmolowik** [bosch-thermostat/home-assistant-bosch-custom-component#114]
**Describe the bug**
There is new version of firmware, so now integration stop working with message: You might have unsuporrted firmware version 03.08.01.

**To Reproduce**
1. Enable integration for CT200 with upograded firmware to 03.08.01

**Expected behavior**
Integration should work with new firmware

**Version**
  - Home Assistant 2021.11.5
  - HA Bosch component 0.16.6

** Debug SCAN **
[bosch_scan.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/7648340/bosch_scan.txt)

**Comment by tomvanswam** [comment]
Same here

** Debug SCAN **
[bosch_scan.json.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/7649586/bosch_scan.json.txt)

**Comment by bonepl** [comment]
Same here

**Comment by pszafer** [comment]
Check new release: https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.16.7

**Comment by tomvanswam** [comment]
> Check new release: https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.16.7

That is uber fast! Thanks a bunch!

**Comment by tomvanswam** [comment]
Updates and restarted ha last evening and all was working well.
However after a automaten restar of ha this night i hot the following logging and a not startend integration:

Logger: bosch_thermostat_client.gateway.easycontrol
Source: /usr/local/lib/python3.9/site-packages/bosch_thermostat_client/gateway/easycontrol.py:100
First occurred: 03:18:55 (1 occurrences)
Last logged: 03:18:55

Couldn't find device model. Got product ID: None

And

This error originated from a custom integration.

Logger: custom_components.bosch
Source: custom_components/bosch/__init__.py:256
Integration: Bosch thermostat (documentation, issues)
First occurred: 03:18:55 (1 occurrences)
Last logged: 03:18:55

Your device is unknown null


Ok, after a restart of ha just now, it's working again.
Maybe my internet was down during reboot? Buy shouldn't the integration periodically try to connect again? Instead of disabling itself in error state?

**Comment by aleksandersmolowik** [comment]
For me it is working. Thank you!

**Comment by pszafer** [comment]
@tomvanswam if internet is down during normal operation then component will reconnect. If it can't connect or authenticate during start up it won't reload automatically. This is prevention. If user typed wrong password and I would try to reconnect every x minutes server might block public IP and it would make only more problems. Unfortunately I can't recognize with 100% accuracy if I can't connect to xmpp because of faulty internet vs wrong credentials.

**Comment by tomvanswam** [comment]
Thanks for the clear response!

**Comment by webeling67** [comment]
@tomvanswam Is this resolved in your view?
