### ISSUE TITLE
50% of all entities missing for km200 / ip-inside 

### ISSUE THREAD

**Issue by tp1de** [bosch-thermostat/home-assistant-bosch-custom-component#176]
Coming from ioBroker I installed home assistant some 4 days ago to check if it is worthwhile considering to move to ha.
For ioBroker I wrote an adapter to read the ems-esp and km200 API and create the states (entities).

Compared to my ioBroker-adapter (screening the km200 API for all states),  I now get just less than 50% of the states using this custom component in ha. 

I have quite some difficulties in understanding the coding practice in ha and for your component. 
I can't find the logic where you select the km200 states/fields to be read. 
Is this fixed or do you read through all the km200 structure? 

BTW: Why are most entities inactive and have to activated manually?

**Comment by pszafer** [comment]
I guess we can figure out it on discord.
Component present only entities which are used by HA entities and have meaningful states. Rest are not fetched as it doesn't make sense imo.
Most entities are inactive because there were people who had problems with API locked out by bosch servers, because of too many requests.
