### ISSUE TITLE
Meaning of some sensors

### ISSUE THREAD

**Issue by BooBoss** [bosch-thermostat/home-assistant-bosch-custom-component#241]
Sorry - I know this is for reporting issues and not asking general questions but I don't see any other place where I can ask. 

I just want to ask what those sensors actually mean? What information they provide?

![image](https://user-images.githubusercontent.com/40237421/204645008-1c30666e-a330-4a3b-96a8-3d1206c70402.png)

For example this ractualTemp compared with outdoor temp looks like this:

![image](https://user-images.githubusercontent.com/40237421/204645203-2e7e46e8-10d6-4111-8eaa-a7349fd312dd.png)

**Comment by honikos** [comment]
Hi BooBoos,
I do not have so much experience in using this integration, nor with heat pumps. But as well I am using this nice integration I try to interpret this entities.  
This is my suggestion:
In your example this are all recording sensors from the bosch device, except the "outdoor temperatur" sensor in your chart.
E.g. the "recording routdoor_t1" records the outdoor temperature from sensor t1once every hour, whereas the "outdoor temperature" is pulled form homeassistant (ha) every minute(?). 
I assume the recording sensor from the bosch device is storing his data within the bosch device storage, whereas the pulled values are stored only in ha and not in the bosch device storage.
In the end, the recording sensors do not give more information because it seems the pulled senors from ha give you more detailed information with higher resolution. My recording sensors only have one value every hour and I assume the bosch api is pushing this values into the network.
This are my ideas and I hope to get detailed information for dummys.

**Comment by BooBoss** [comment]
> Hi BooBoos, I do not have so much experience in using this integration, nor with heat pumps. But as well I am using this nice integration I try to interpret this entities. This is my suggestion: In your example this are all recording sensors from the bosch device, except the "outdoor temperatur" sensor in your chart. E.g. the "recording routdoor_t1" records the outdoor temperature from sensor t1once every hour, whereas the "outdoor temperature" is pulled form homeassistant (ha) every minute(?). I assume the recording sensor from the bosch device is storing his data within the bosch device storage, whereas the pulled values are stored only in ha and not in the bosch device storage. In the end, the recording sensors do not give more information because it seems the pulled senors from ha give you more detailed information with higher resolution. My recording sensors only have one value every hour and I assume the bosch api is pushing this values into the network. This are my ideas and I hope to get detailed information for dummys.

Thank you for your reply. I interpret it the same way as you wrote but wasn't sure if I'm right. Now I have confirmation :-) Yes - it is pulled every one hour and it also has one hour delay from "real-time" sensors (but that's not a problem). You can see it when you compare recorded energy consumption with real time heat pump modulation. The whole thing is that I want to see energy consumption and heat pump does not provide real time sensor for that - only this recorded one. I'm wondering if I can rely on that recorded energy consumption. If it's pulled once an hour then is it mathematical avarage from that hour? I mean - is it really accurate? Also this recorded values do not store decimal numbers what also causes my concerns about accuracy.

**Comment by pszafer** [comment]
Hi, recording sensors are only valuable for energy consumption.
With new api turned on even more (check out wiki).
"Normal" energy consumption sensors are not working reliable for most users, so component is downloading data from recording sensor.

**Comment by BooBoss** [comment]
In other words recording sensors are reliable in terms of monitoring energy consumption. Thanks for an answer!

P.S. Czy mi się wydaje czy my wszyscy tutaj jesteśmy Polakami? :P

**Comment by pszafer** [comment]
No, I'm Polish but there are Czech, Slovakia, Slovenia, Italian, German, Dutch, Belgium, France, Great Britain, Sweden. So almost all Europe;)

**Comment by BooBoss** [comment]
:-)
