### ISSUE TITLE
RC300 sensor hotwater temp unavailable

### ISSUE THREAD

**Issue by flexstarr** [bosch-thermostat/home-assistant-bosch-custom-component#249]
**Describe the bug**
sensor hotwater temp is not showing a value:
`Can't update data. Error: URI /system/sensors/temperatures/hotWater_t2 doesn not exist: 404, message='Not Found', url=URL('http://therme.home/system/sensors/temperatures/hotWater_t2')`

but a value is shown on the dws1 graph, so the value is available somewhere.

**Expected behavior**
hotwater temp is shown

**Screenshots**
![image](https://user-images.githubusercontent.com/1353925/208236195-1056634a-93fc-40dd-990c-14a3cbce25cc.png)
![image](https://user-images.githubusercontent.com/1353925/208236248-9414224e-ec50-4302-a88a-ccfc8643657e.png)
![image](https://user-images.githubusercontent.com/1353925/208236260-757e8795-251d-4f88-a57f-9ae2b799290d.png)

**Version**
  - 2022.12.06
  - HA Bosch component version: 0.20
  - Python Bosch HTTP client version?

**Additional context**
wondering how to get to a working sensor. any help appreciated!

**Comment by henriksi** [comment]
Hi guys, 

I have a similar issue on KM100/RC310 system setup with the "Actual HC1 supply temperature". 

**Describe the bug**

Actual HC supply temperature is not shown a value: `Can't update data. Error: URI /heatingCircuits/hc1/actualSupplyTemperature doesn not exist: 404, message='Not Found', url=URL('http://192.168.178.51/heatingCircuits/hc1/actualSupplyTemperature')
`
**Expected behaviour**

Sensor value should be shown. The RC310 shows this value - it is a additional sensor behind the hydraulic switch (so not the same as heat soruce/ burnes supply temp - those values are given (twice even)). 

Debug Scan: 
[bosch_scan_hs.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/10286215/bosch_scan_hs.txt)

Would appreciate any hint on that.

**Comment by pszafer** [comment]
Use template sensor and extract attribute from water heater entity.

**Comment by flexstarr** [comment]
Yeah, that will do the trick then, also wondering if it could be read out instantly from another source of information, maybe something like 'hotWater_t1'.

**Comment by pszafer** [comment]
There is sensor `hotWater_t2`, you could use that.
