### ISSUE TITLE
Energy Dashboard: First value of the day wrong (too high)

### ISSUE THREAD

**Issue by achi87** [bosch-thermostat/home-assistant-bosch-custom-component#318]
**Describe the bug**
Energy Dashboard (new statistic api):
Over the day the solaryield recording value of the first hour of the day with yield>0 rises (every hour?) and is way too high at the end of the day.
Screenshots show the same day at 3 different times. 
Value (12:00-13:00) is correct at 15:39 and gets bigger (see 18:47 and 19:2).

**To Reproduce**
Use new statistic api for record values (solar, ch, dhw) . 

**Screenshots**
![Screenshot_20230821-153940](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/95137943/136214e4-e303-48d4-95bc-b14d464f69fc)
![Screenshot_20230821-184739](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/95137943/98e43b85-529b-47dd-80eb-086743b407aa)
![Screenshot_20230821-192114](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/95137943/4764c2c9-e45f-4e5d-803d-188dc4d44f63)

**Version**
  - HA version 2023.8.1
  - HA Bosch component version 0.23.2

** Debug SCAN **
https://drive.google.com/file/d/145_q7vAubtqRHgQmXWFladxCCWg8tk1Y/view?usp=drivesdk

**Comment by achi87** [comment]
Not a special issue regarding the solaryield.
ActualCHpower is also getting bigger over the day 
![Screenshot_20230826-130711](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/95137943/9b09e904-08cf-42b9-beb0-0b23e5b781cf)
![Screenshot_20230826-160211](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/95137943/d0d556c6-0f16-4f54-bdc6-4d24ee967bf0)

**Comment by achi87** [comment]
fyi:
My workaround is to delete the recording-statistics of the current day at 23:50.
With the next "run" the data for the whole day is added again and stays correct.

**Comment by pszafer** [comment]
Please check out https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.23.3
I will reopen if problem'd still occur.

**Comment by achi87** [comment]
Looks good for todays data.
Thanks a lot!

**Comment by achi87** [comment]
> Please check out https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.23.3 I will reopen if problem'd still occur.

Unfortunately the problem does still occur with the dhw recording (maybe also ch, it's still too warm to see).
Solaryield looks fine.

![Screenshot_20231001-211554](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/95137943/fb0f6308-19af-4e76-ad0b-800bcd7523ca)
![Screenshot_20231001-211503](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/95137943/0fdf7b84-7652-4646-816c-3451cbd914a3)

**Comment by pszafer** [comment]
Please enable debug logs, find relevant ones and attach here.

**Comment by achi87** [comment]
> Please enable debug logs, find relevant ones and attach here.

The dhwpower-value today 13-14 was 2.7.
Looks like the 2.7 are added to the "sum" every following hour.
Find the log attached. I hope this helps and thanks a lot for your effort!!

[bosch_home-assistant_short.log](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/12795655/bosch_home-assistant_short.log)
[bosch_home-assistant.log](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/12795656/bosch_home-assistant.log)

**Comment by pszafer** [comment]
I'll take another look at this. What timezone are you in? Is HA timezone same as your device?

**Comment by achi87** [comment]
I'm in GMT+1 (Berlin).
HA and device have the same time.

**Comment by birefringence** [comment]
It looks like the "sum" field is not calculated correctly. I set it up initially and somehow it starts with the value 277 instead of 0:
`sqlite> select * from statistics where metadata_id=68;
229672|||||||8.0|277.0|68|1697436392.31216|1697432400.0|
229732|||||||2.0|279.0|68|1697439960.86276|1697436000.0|
229792|||||||3.0|282.0|68|1697443560.80928|1697439600.0|
229853|||||||1.0|283.0|68|1697447160.79825|1697443200.0|
229914|||||||1.0|284.0|68|1697450760.81171|1697446800.0|
229974|||||||2.0|286.0|68|1697454360.78511|1697450400.0|
230038|||||||1.0|287.0|68|1697457962.15749|1697454000.0|
230096|||||||1.0|288.0|68|1697461560.79043|1697457600.0|
230157|||||||1.0|289.0|68|1697465160.83549|1697461200.0|
230278|||||||1.0|290.0|68|1697472360.81009|1697468400.0|
230339|||||||1.0|291.0|68|1697475960.84639|1697472000.0|
230400|||||||1.0|292.0|68|1697479560.84954|1697475600.0|
230460|||||||1.0|293.0|68|1697483160.82669|1697479200.0|
230522|||||||1.0|294.0|68|1697486760.86455|1697482800.0|
230583|||||||1.0|295.0|68|1697490360.87519|1697486400.0|`

I tried fixing it manually while HA was shut down:
`sqlite> select * from statistics where metadata_id=68;
229672|||||||8.0|8.0|68|1697436392.31216|1697432400.0|
229732|||||||2.0|10.0|68|1697439960.86276|1697436000.0|
229792|||||||3.0|13.0|68|1697443560.80928|1697439600.0|
229853|||||||1.0|14.0|68|1697447160.79825|1697443200.0|
229914|||||||1.0|15.0|68|1697450760.81171|1697446800.0|
229974|||||||2.0|17.0|68|1697454360.78511|1697450400.0|
230038|||||||1.0|18.0|68|1697457962.15749|1697454000.0|
230096|||||||1.0|19.0|68|1697461560.79043|1697457600.0|
230157|||||||1.0|20.0|68|1697465160.83549|1697461200.0|
230278|||||||1.0|21.0|68|1697472360.81009|1697468400.0|
230339|||||||1.0|22.0|68|1697475960.84639|1697472000.0|
230400|||||||1.0|23.0|68|1697479560.84954|1697475600.0|
230460|||||||1.0|24.0|68|1697483160.82669|1697479200.0|
230522|||||||1.0|25.0|68|1697486760.86455|1697482800.0|
230583|||||||1.0|26.0|68|1697490360.87519|1697486400.0|`

But then after starting HA again, it looked like this:
`sqlite> select * from statistics where metadata_id=68;
229672|||||||8.0|34.0|68|1697436392.31216|1697432400.0|
229732|||||||2.0|36.0|68|1697439960.86276|1697436000.0|
229792|||||||3.0|39.0|68|1697443560.80928|1697439600.0|
229853|||||||1.0|40.0|68|1697447160.79825|1697443200.0|
229914|||||||1.0|41.0|68|1697450760.81171|1697446800.0|
229974|||||||2.0|43.0|68|1697454360.78511|1697450400.0|
230038|||||||1.0|44.0|68|1697457962.15749|1697454000.0|
230096|||||||1.0|45.0|68|1697461560.79043|1697457600.0|
230157|||||||1.0|46.0|68|1697465160.83549|1697461200.0|
230278|||||||1.0|47.0|68|1697472360.81009|1697468400.0|
230339|||||||1.0|48.0|68|1697475960.84639|1697472000.0|
230400|||||||1.0|49.0|68|1697479560.84954|1697475600.0|
230460|||||||1.0|50.0|68|1697483160.82669|1697479200.0|
230522|||||||1.0|51.0|68|1697486760.86455|1697482800.0|
230583|||||||1.0|52.0|68|1697490360.87519|1697486400.0|`

26 + 8 is 34.

This is for recording:ractualchpowerexternal.

**Comment by birefringence** [comment]
OK, not sure if I'm actually seeing the same issue here. I fixed all the sums again manually on the second day, and now everything looks fine. So for me there was only a problem when there was less than one day of data available.

**Comment by achi87** [comment]
With the colder temperatures I did check the recs more the last few days and it seems like the values are correct and stay correct.
Fine for me.
