### ISSUE TITLE
Unknown error occurred (adding new easycontrol CT200)

### ISSUE THREAD

**Issue by mr4hughz** [bosch-thermostat/home-assistant-bosch-custom-component#331]
when adding new easycontrol CT200 thermostat 

when adding from hacs no issues, (restart HA), add intergration --> select "easy control"  next screen "user data" 

Unknown error occurred (can't thell what goes wrong) 

FYI:  no "-" between ID/token en 8 char "simple" passwd (no special characters used) 

-------------------------------------------------------------------------
<facepalm> 

When using OCR one might need to check if the text = 1:1 copied y/n ... 1 letter was erroronously capitalized and thus caused the error (yes it is fixed now) aka PEBKAC

please change error to "you might want to double check the stickers & input in the app"  this might benifit new users ;)

**Comment by pszafer** [comment]
The problem is that if access token is properly provided then bosch server doesn't respond that password is wrong...
and sometimes data can't be decoded (then I got notification about wrong password for sure), but sometimes it just doesn't respond with data... and then it can be dns issue, password issue etc. Hard to guess.

**Comment by pietvdmaas** [comment]
Is some who can help with this issue. I've the same problem. 
Installed 0.24.5 and trying to add my Nefit CT200 (XMPP).

Changed password already 2 times, but no result
